### ISSUE TITLE
Implementar hover

### ISSUE THREAD

**Issue by lucianotonet** [agenciamav/juscchneider.com#1]
No bloco vermeho em destaque, único com subtítulo, implementar o efeito hover NICE LILY (primeiro da lista ->  http://tympanus.net/Development/HoverEffectIdeas/index.html) 

![image](https://cloud.githubusercontent.com/assets/2693019/14512554/6bf4da20-01b6-11e6-8d8c-f74ed4790863.png)

**Comment by ghost** [comment]
Concluido !

**Comment by lucianotonet** [comment]
Só faltou tirar o subtítulo, mas pode deixar que eu removo...

![untitled-1](https://cloud.githubusercontent.com/assets/2693019/14539682/be202d80-0257-11e6-9181-26de11ecc4ba.jpg)

![image](https://cloud.githubusercontent.com/assets/2693019/14539538/2a839b84-0257-11e6-833e-4d973c297262.png)
